USE cloc;

ALTER TABLE cloc_cities
	MODIFY COLUMN population BIGINT DEFAULT 100000,
    MODIFY COLUMN iron_mines INT DEFAULT 1,
    MODIFY COLUMN coal_mines INT DEFAULT 1,
    MODIFY COLUMN oil_wells INT DEFAULT 1;

ALTER TABLE cloc_policy
	MODIFY COLUMN manpower_change BIGINT DEFAULT -2,
    MODIFY COLUMN food_change BIGINT DEFAULT -2,
    MODIFY COLUMN economy_change BIGINT DEFAULT -2,
    MODIFY COLUMN fortification_change BIGINT DEFAULT -2,
    MODIFY COLUMN farming_subsidies_change BIGINT DEFAULT -2;

CREATE TABLE anti_spam(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user INT,
    action ENUM('SEND_RESOURCE', 'SEND_DECLARATION', 'SEND_INVITE', 'UPDATE_FLAG', 'UPDATE_PORTRAIT', 'UPDATE_ALLIANCE_FLAG'),
    time BIGINT,
    FOREIGN KEY (user) REFERENCES cloc_login (id) ON DELETE CASCADE
);

CREATE TABLE modifiers(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user INT,
	type TEXT,
	start BIGINT,
	FOREIGN KEY (user) REFERENCES cloc_login (id) ON DELETE CASCADE
);

ALTER TABLE modifiers
	ADD COLUMN city INT AFTER user;

ALTER TABLE modifiers
	ADD CONSTRAINT FOREIGN KEY (city) REFERENCES cloc_cities (id) ON DELETE CASCADE