ALTER TABLE anti_spam
	MODIFY COLUMN action ENUM ('SEND_RESOURCE', 'SEND_DECLARATION', 'SEND_INVITE', 'UPDATE_FLAG', 'UPDATE_PORTRAIT', 'UPDATE_ALLIANCE_FLAG', 'MESSAGE');

ALTER TABLE nation_stats
    ADD COLUMN max_fighters INT DEFAULT -1,
	ADD COLUMN max_bombers INT DEFAULT -1,
	ADD COLUMN max_recon INT DEFAULT -1;

ALTER TABLE nation_stats
	ADD COLUMN current_fighters INT DEFAULT 0,
    ADD COLUMN current_bombers INT DEFAULT 0,
    ADD COLUMN current_recon INT DEFAULT 0;