package net.watersfall.clocgame.model.decisions;

public enum CityDecisions
{
	BUILD_COAL_MINE,
	BUILD_IRON_MINE,
	BUILD_OIL_WELL,
	BUILD_CIVILIAN_INDUSTRY,
	BUILD_MILITARY_INDUSTRY,
	BUILD_NITROGEN_INDUSTRY,
	BUILD_UNIVERSITY,
	BUILD_PORT,
	BUILD_BARRACK,
	BUILD_RAILROAD,
	REMOVE_COAL_MINE,
	REMOVE_IRON_MINE,
	REMOVE_OIL_WELL,
	REMOVE_CIVILIAN_INDUSTRY,
	REMOVE_MILITARY_INDUSTRY,
	REMOVE_NITROGEN_INDUSTRY,
	REMOVE_UNIVERSITY,
	REMOVE_PORT,
	REMOVE_BARRACK,
	REMOVE_RAILROAD
}
