package com.watersfall.clocgame.model.database;

public enum Tables
{
	ANTI_SPAM,
	CLOC_ARMY,
	CLOC_CITIES,
	CLOC_COSMETIC,
	CLOC_DECLARATIONS,
	CLOC_DOMESTIC,
	CLOC_ECONOMY,
	CLOC_FOREIGN,
	CLOC_LOGIN,
	CLOC_MAIN,
	CLOC_MILITARY,
	CLOC_NEWS,
	CLOC_POLICY,
	CLOC_TECH,
	CLOC_TREATIES,
	CLOC_TREATIES_MEMBERS,
	CLOC_TREATY_INVITES,
	CLOC_WAR,
	CLOC_WAR_LOGS,
	EVENTS,
	FACTORIES,
	GLOBAL_STATS_HISTORY,
	MESSAGES,
	MODIFIERS,
	NATION_HISTORY,
	PRODUCTION
}
