package com.watersfall.clocgame.constants;

public class Costs
{
	public static final int CRACKDOWN = 100;
	public static final int FREE = 100;
	public static final int ALIGN_ENTENTE = 100;
	public static final int ALIGN_CENTRAL_POWERS = 100;
	public static final int ALIGN_NEUTRAL = 100;
	public static final int CONSCRIPT_MANPOWER = 2000;
	public static final int MINE_BASE = 500;
	public static final int MINE_MULT = 50;
	public static final int OIL_BASE = 500;
	public static final int OIL_MULT = 100;
	public static final int FACTORY_BASE_IRON = 50;
	public static final int FACTORY_BASE_COAL = 25;
	public static final int FACTORY_BASE_STEEL = 0;
	public static final int FACTORY_MULT_IRON = 50;
	public static final int FACTORY_MULT_COAL = 25;
	public static final int FACTORY_MULT_STEEL = 2;
	public static final int UNIVERSITY_BASE_IRON = 100;
	public static final int UNIVERSITY_BASE_COAL = 75;
	public static final int UNIVERSITY_BASE_STEEL = 5;
	public static final int UNIVERSITY_MULT_IRON = 150;
	public static final int UNIVERSITY_MULT_COAL = 100;
	public static final int UNIVERSITY_MULT_STEEL = 5;
	public static final int RAILWAY_BASE = 5000;
	public static final int RAILWAY_MULT = 2500;
	public static final int PORT_BASE = 5000;
	public static final int PORT_MULT = 2500;
	public static final int BARRACKS_BASE = 5000;
	public static final int BARRACKS_MULT = 2500;
	public static final int SHIP_SUBMARINE_STEEL = 10;
	public static final int MULT_SHIP_SUBMARINE_STEEL = 1;
	public static final int SHIP_SUBMARINE_COAL = 10;
	public static final int MULT_SHIP_SUBMARINE_COAL = 1;
	public static final int SHIP_DESTROYER_STEEL = 10;
	public static final int MULT_SHIP_DESTROYER_STEEL = 1;
	public static final int SHIP_DESTROYER_COAL = 10;
	public static final int MULT_SHIP_DESTROYER_COAL = 1;
	public static final int SHIP_CRUISER_STEEL = 10;
	public static final int MULT_SHIP_CRUISER_STEEL = 1;
	public static final int SHIP_CRUISER_COAL = 10;
	public static final int MULT_SHIP_CRUISER_COAL = 1;
	public static final int SHIP_PRE_BATTLESHIP_STEEL = 10;
	public static final int MULT_SHIP_PRE_BATTLESHIP_STEEL = 1;
	public static final int SHIP_PRE_BATTLESHIP_COAL = 10;
	public static final int MULT_SHIP_PRE_BATTLESHIP_COAL = 1;
	public static final int SHIP_BATTLESHIP_STEEL = 10;
	public static final int MULT_SHIP_BATTLESHIP_STEEL = 1;
	public static final int SHIP_BATTLESHIP_COAL = 10;
	public static final int MULT_SHIP_BATTLESHIP_COAL = 1;
	public static final int SHIP_TRANSPORT_STEEL = 10;
	public static final int MULT_SHIP_TRANSPORT_STEEL = 1;
	public static final int SHIP_TRANSPORT_COAL = 10;
	public static final int MULT_SHIP_TRANSPORT_COAL = 1;
}
